version: "3.5"

services:
  devcontainer:
    image: "esp-scheduler/devcontainer:${BUILD_VERSION}"
    build:
      context: devcontainer
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - ./.env
    command: sleep infinity
